name: Set up Go

runs:
  using: composite
  steps:
    - uses: actions/setup-go@v6
      with:
        go-version-file: go.work
        cache-dependency-path: |
          go.work.sum
          internal/go-generate/go/go.sum
          third-party/*/go.sum
          third-party/traefik/dynamic-ext/go.sum
