apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: servicenetworkendpointgroups.networking.gke.io
spec:
  conversion:
    strategy: None
  group: networking.gke.io
  names:
    kind: ServiceNetworkEndpointGroup
    listKind: ServiceNetworkEndpointGroupList
    plural: servicenetworkendpointgroups
    shortNames:
      - svcneg
    singular: servicenetworkendpointgroup
  scope: Namespaced
  versions:
    - name: v1beta1
      schema:
        openAPIV3Schema:
          properties:
            apiVersion:
              description: "APIVersion defines the versioned schema of this representation of
                an object. Servers should convert recognized schemas to the
                latest internal value, and may reject unrecognized values. More
                info:
                https://git.k8s.io/community/contributors/devel/sig-architectur\
                e/api-conventions.md#resources"
              type: string
            kind:
              description: "Kind is a string value representing the REST resource this object
                represents. Servers may infer this from the endpoint the client
                submits requests to. Cannot be updated. In CamelCase. More info:
                https://git.k8s.io/community/contributors/devel/sig-architectur\
                e/api-conventions.md#types-kinds"
              type: string
            metadata:
              type: object
            spec:
              type: object
            status:
              description: ServiceNetworkEndpointGroupStatus is the status for a
                ServiceNetworkEndpointGroup resource
              properties:
                conditions:
                  description: Last time the NEG syncer syncs associated NEGs.
                  items:
                    description: NegCondition contains details for the current condition of this
                      NEG.
                    properties:
                      lastTransitionTime:
                        description: Last time the condition transitioned from one status to another.
                        format: date-time
                        nullable: true
                        type: string
                      message:
                        description: A human readable message indicating details about the transition.
                          This field may be empty.
                        type: string
                      observedGeneration:
                        description: ObservedGeneration will not be set for ServiceNetworkEndpointGroup
                          as the spec is empty.
                        format: int64
                        type: integer
                      reason:
                        description: The reason for the condition's last transition
                        type: string
                      status:
                        description: Status of the condition, one of True, False, Unknown.
                        type: string
                      type:
                        description: Type is the type of the condition.
                        type: string
                    required:
                      - type
                      - status
                      - lastTransitionTime
                      - reason
                      - message
                    type: object
                  type: array
                  x-kubernetes-list-map-keys:
                    - type
                  x-kubernetes-list-type: map
                lastSyncTime:
                  description: Last time the NEG syncer syncs associated NEGs.
                  format: date-time
                  nullable: true
                  type: string
                networkEndpointGroups:
                  items:
                    description: NegObjectReference is the object reference to the NEG resource in
                      GCE
                    properties:
                      id:
                        description: The unique identifier for the NEG resource in GCE API.
                        type: string
                      networkEndpointType:
                        description: "NetworkEndpointType: Type of network endpoints in this network
                          endpoint group."
                        type: string
                      selfLink:
                        description: SelfLink is the GCE Server-defined fully-qualified URL for the GCE
                          NEG resource
                        type: string
                    required:
                      - id
                    type: object
                  type: array
                  x-kubernetes-list-map-keys:
                    - id
                  x-kubernetes-list-type: map
              type: object
          type: object
      served: true
      storage: true
