name: Snapshot Release
on:
  push:
    branches:
      - snapshot
      - snapshots/**
  pull_request:

jobs:
  release:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' || contains(github.event.pull_request.labels.*.name, 'snapshot') }}
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ./.github/actions/install-deps
      - uses: ./.github/actions/build-packages
      - name: Bump package version
        run: pnpm changeset version --snapshot
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish snapshot packages
        run: pnpm publish -r --tag snapshot --no-git-checks
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
