name: Test
on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/install-deps
      - uses: ./.github/actions/build-packages
      - name: Lint files
        run: pnpm run lint
  test:
    runs-on: ubuntu-latest
    needs:
      - lint
    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x, 20.x]
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/install-deps
        with:
          node-version: ${{ matrix.node-version }}
      - uses: ./.github/actions/build-packages
      - name: Run unit tests
        run: pnpm run test
